### ISSUE TITLE
Bug after prepare

### ISSUE THREAD

**Issue by 60percentCaffeine** [TeslaCloud/TTTRewrite#1]
After preparing the Innocents always win.
Я не очень хорош в англицком, потому напишу тут: после подготовки, та команда, за которую играю я, сразу же выигрывает. Тестирую с ботами. И еще, добавьте русскую локализацию.

**Comment by Meow** [comment]
Это баг который я закрыл в приватной версии. Сегодня залью в публичную фикс тогда.

**Comment by 60percentCaffeine** [comment]
Сегодня как-бы уже прошло...

**Comment by Meow** [comment]
Извиняюсь конечно, но я не ванга. Я постараюсь залить настолько скоро насколько оно возможно, но у меня пока проблемы с тестом кода.

**Comment by Meow** [comment]
Починил.
